import express, { Request, Response, NextFunction } from 'express'
import Shopify from '@shopify/shopify-api'
import { Shop, Long, Grand, SavedLong, Customers, Quota, Rapid, RapidChild, SavedRapid } from '../../models/shop-model'
import checkAuth, { checkApiAuth } from '../middlewares/check-auth'
import { deleteIncompleteLogin } from '../middlewares/experimental'
import { templateGate } from '../quotas'
import { forCommon, forStarter, forStandard, forUltimate } from './price-plan'
import { divide, renderFor } from '../render-divider'
import { generateDiscountCode } from '../functions'